### ISSUE TITLE
"Loading the module for the configuration unit failed." When using components

### ISSUE THREAD

**Issue by ShannyMan** [microsoft/VisualStudioDSC#14]
I'm attempting to install and configure Visual Studio using the `Components` option versus the `VSConfigFile`. When I run the winget configure, I get the below error:

_"Loading the module for the configuration unit failed."_

![image](https://github.com/microsoft/VisualStudioDSC/assets/29736122/89393d1a-ef31-4505-88c9-00411f5ec8ea)

Here is my yaml:
```
properties:
  configurationVersion: 0.2.0

  resources:

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Visual Studio 2022 Community Edition
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget

    - resource: Microsoft.VisualStudio.DSC/VSComponents
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS Workloads
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release
        includeRecommended: true
        components:
          - Microsoft.VisualStudio.Workload.Azure
          - Microsoft.VisualStudio.Workload.ManagedDesktop
          - Microsoft.VisualStudio.Workload.Data
          - Microsoft.VisualStudio.Workload.NetCrossPlat
          - Microsoft.VisualStudio.Workload.NetWeb
          - Microsoft.VisualStudio.Workload.Universal
```

Is there something I'm missing or doing wrong?

Thank you!
