### ISSUE TITLE
VSComponents not working with winget configure

### ISSUE THREAD

**Issue by flowcoder1** [microsoft/VisualStudioDSC#17]
I can't get winget configure to install Visual Studio components with the current version (https://www.powershellgallery.com/packages/Microsoft.VisualStudio.DSC/1.0.18-beta). Once I do a `Install-Module -Name Microsoft.VisualStudio.DSC -RequiredVersion 1.0.15-beta -AllowPrerelease` then `(Get-DscResource VSComponents).Properties` works and so does the winget configuration file:

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/terminal#prerequisites
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 (any edition is OK)
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release        
        components:
          - Microsoft.VisualStudio.Workload.ManagedDesktop
          - Microsoft.VisualStudio.Workload.Universal
  configurationVersion: 0.2.0
```
See https://github.com/microsoft/winget-cli/issues/3914 for discussion.
