### ISSUE TITLE
 The configuration unit failed while attempting to apply the desired state.

### ISSUE THREAD

**Issue by PShipstone** [microsoft/VisualStudioDSC#19]
Hi,  could you please give me some direction for the following error when trying to install Visual Studio workloads:

We're using **Microsoft.VisualStudio.DSC v1.0.19**

I've included the whole winget YAML config file here but you're probably only interested in the Visual Studio install aspect (2nd and 3rd resource)

```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:   
    - resource: WinGetPackage
      id: Git
      directives:
        module: Microsoft.WinGet.DSC
        description: Install Git
        allowPrerelease: false
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VisualStudio
      directives:
        description: Install Visual Studio 2022 Professional
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudio.2022.Professional
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      dependsOn:
        - VisualStudio
      directives:
        description: Install required VS workloads from project .vsconfig file
        allowPrerelease: false
      settings:
        productId: Microsoft.VisualStudio.2022.Professional
        channelId: VisualStudio.17.Release
        includeRecommended: true
        components:
          - Microsoft.VisualStudio.Workload.NetWeb
    - resource: WinGetPackage
      id: VSCode
      directives:
        module: Microsoft.WinGet.DSC
        description: Install Microsoft Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: WinGetPackage
      id: Postman
      directives:
        module: Microsoft.WinGet.DSC
        description: Install Postman
        allowPrerelease: false
      settings:
        id: Postman.Postman
        source: winget
    - resource: WinGetPackage
      id: Notepad++
      directives:
        module: Microsoft.WinGet.DSC
        description: Install Notepad++
        allowPrerelease: false
      settings:
        id: Notepad++.Notepad++
        source: winget
    - resource: WinGetPackage
      id: GitHubDesktop
      directives:
        module: Microsoft.WinGet.DSC
        description: Install GitHub Desktop
        allowPrerelease: false
      settings:
        id: GitHub.GitHubDesktop
        source: winget   
    - resource: WinGetPackage
      id: WinMerge
      directives:
        module: Microsoft.WinGet.DSC
        description: Install WinMerge
        allowPrerelease: false
      settings:
        id: WinMerge.WinMerge
        source: winget        
    - resource: PSDscResources/Script
      id: VSCode-Extensions
      directives:
        description: Install VSCode extensions
        allowPrerelease: false
      settings:
        GetScript: |
          # Your custom PowerShell code to check app configuration
        TestScript: |
          return $false
        SetScript: |
          # PowerShell script commands to install VSCode extensions
          Start-Process -WindowStyle Hidden code "--install-extension jebbs.plantuml" -Wait
          Start-Process -WindowStyle Hidden code "--install-extension yzhang.markdown-all-in-one" -Wait 
  configurationVersion: 0.2.0
```

Powershell Error: 
![image](https://github.com/microsoft/VisualStudioDSC/assets/44038179/d7a2df82-d414-4e05-bb71-12767384ca07)

Log:
![image](https://github.com/microsoft/VisualStudioDSC/assets/44038179/1edb4732-2970-4b8e-90e6-c4f1eb352863)
